[dev]
  command = "yarn nuxt start"
  framework = "#custom"
  functions = ".nuxt/serverless/netlify"
  port = 8888
  targetPort = 3000

[build]
  command = "yarn generate"
  publish = "dist"
  functions = ".nuxt/serverless/netlify"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/_nuxt"
  status = 200
